version: "3.9"

services:
  web:
    build: .
    container_name: omnix_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: omnix_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omnix
      MYSQL_USER: omnix_user
      MYSQL_PASSWORD: omnix_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: omnix_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: omnix_user
      PMA_PASSWORD: omnix_pass
    depends_on:
      - db

volumes:
  db_data:
